ecs 193/ecs193/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^stebbins/', 'stebbins.views.oldindex'),
    url(r'^/$', include('stebbins.urls', namespace="stebbins")),
    url(r'', include('stebbins.urls', namespace="stebbins")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^messages/', include('django_messages.urls')),
    url(r'^accounts/login/$', 'stebbins.views.login'),
    url(r'^accounts/logout/$', 'stebbins.views.logout'),
    url(r'^accounts/loggedin/$', 'stebbins.views.loggedin'),
    url(r'^accounts/profile/$', 'stebbins.views.profile'),
    url(r'^accounts/invalid/$', 'stebbins.views.invalid_login'),
    url(r'^accounts/register/$', 'stebbins.views.register_user'),
    url(r'^accounts/register_success/$', 'stebbins.views.register_success'),
    url(r'^accounts/internalLogin/$', 'stebbins.views.internalLogin'),
     url(r'^accounts/password_reset/$', 'django.contrib.auth.views.password_reset', kwargs={'template_name' : 'password_reset.html'}),
    url(r'^accounts/password_reset_done/$', 'django.contrib.auth.views.password_reset_done', kwargs={'template_name' : 'password_reset_done.html'}, name='password_reset_done'),
    url(r'^accounts/password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', kwargs={'template_name' : 'password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^accounts/activate/(?P<userName>\w{1,50})/(?P<activation_key>\w{1,50})/$', 'stebbins.views.activate'),
	url(r'^web-players-status/$', 'stebbins.views.webLoggedIn'),
    url(r'^game-players-status/$', 'stebbins.views.internalLoggedIn'),
    url(r'^accounts/password_reset/$', 'django.contrib.auth.views.password_reset'),
    url(r'^accounts/password_reset_done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^accounts/password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^accounts/password_reset_complete/$', 'django.contrib.auth.views.password_reset_complete',  name='password_reset_complete'),
    url(r'^downloads/$', 'stebbins.views.downloads'),
    url(r'^accounts/edit/$', 'stebbins.views.edit_profile'),
    url(r'^accounts/edit_profile_success/$', 'stebbins.views.edit_profile_success'),
    url(r'^accounts/change_password/$', 'stebbins.views.change_password'),
    url(r'^accounts/change_password_success/$', 'stebbins.views.change_password_success'),
    url(r'^compose_success/$', 'stebbins.views.compose_success'),    
    url(r'^send_something/$', 'stebbins.views.send_something'),
    url(r'^forum/forum/(\d+)/$', 'forum.views.forum'),
    url(r'^forum/thread/(\d+)/$', 'forum.views.thread'), 
    url(r'^forum/post/(new_thread|reply)/(\d+)/$', 'forum.views.post'),
    url(r'^forum/reply/(\d+)/$', 'forum.views.reply'),
    url(r'^forum/profile/(\d+)/$', 'forum.views.profile'),
    url(r'^forum/new_thread/(\d+)/$', 'forum.views.new_thread'),
    url(r'^forum/$', 'forum.views.main'),
    url(r'^accounts/internalLogin/$', 'stebbins.views.internalLogin'),
    url(r'^accounts/internalLogout/$', 'stebbins.views.internalLogout'),
    url(r'^accounts/internalUpdate/$', 'stebbins.views.internalUpdate'),
     url(r'^accounts/friends/$', 'stebbins.views.friends'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecs 193/forum/urls.py
from django.conf.urls import include, url, patterns
from forum.models import *

urlpatterns = patterns('forum.views',
    (r"^forum/(\d+)/$", "forum"),
    (r"^thread/(\d+)/$", "thread"),
    (r"^post/(new_thread|reply)/(\d+)/$", "post"),
    (r"^reply/(\d+)/$", "reply"),
    (r"^profile/(\d+)/$", "profile"),
    (r"^new_thread/(\d+)/$", "new_thread"),
    (r"", "main"),
)

ecs 193/stebbins/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^prototype/$', views.prototype, name='prototype'),
    url(r'^accounts/invalid/$', 'stebbins.views.invalid_login'),
    url(r'^ranking', views.ranking, name='ranking'),
]

ecs 193/stebbins/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser
from simple_email_confirmation import SimpleEmailConfirmationUserMixin
from django.contrib.auth.models import UserManager
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.signals import user_logged_in, user_logged_out
import math 
# Create your models here.

'''class UserProfile(models.Model):
    user   = models.OneToOneField(User)
    picture = models.ImageField(upload_to="images")
    REQUIRED_FIELDS = ('user', 'email',)
    
    def __unicode__(self):
        return self.user.usernam'''

class Friends(models.Model):
    name = models.CharField(max_length=31, default = "")
    friends = models.ForeignKey('User', null = True, blank = True)

class LoggedUser(models.Model):
    user = models.ForeignKey('User')
    web = models.BooleanField(default=False)
    internal = models.BooleanField(default=False)

    def __unicode__(self):
        return self.user.userName

    def login_user(sender, request, user, **kwargs):
        try:
            e = LoggedUser.objects.get(user=user)
            if user.login_web is True and e.web is False:
                e.web=user.login_web
                e.save()
            
            elif user.login_internal is True and e.internal is False:
                e.internal=user.login_internal
                e.save()
       
        except LoggedUser.DoesNotExist:
            LoggedUser(user=user, web=user.login_web, internal=user.login_internal).save()

    def logout_user(sender, request, user, **kwargs):
        try:
            e = LoggedUser.objects.get(user=user)
            if user.login_web is False and user.login_internal is True:
                e.web=user.login_web
                e.save()
            elif user.login_internal is False and user.login_web is True:
                e.internal=user.login_internal
                e.save()
            else :
                e.delete()
        except LoggedUser.DoesNotExist:
            pass

    user_logged_in.connect(login_user)
    user_logged_out.connect(logout_user)



class CustomUserManager(BaseUserManager):

    def create_user(self, userName, password=None, **extra_fields):
        userName = userName
        user = self.model(userName=userName, is_staff=False, is_active=True, is_superuser=False, is_admin = False)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, userName, password, **extra_fields):
        userName = userName
        user = self.model(userName=userName, is_staff=False, is_active=True, is_superuser=True, is_admin = True)
        user.set_password(password)
        user.save(using=self._db)
        return user
        


        
class User(SimpleEmailConfirmationUserMixin, AbstractBaseUser):
        posts = models.IntegerField(default=0)
        wins = models.PositiveIntegerField(default = 0)
        losses = models.PositiveIntegerField(default = 0)
        rating = models.FloatField(default = 1000)
        ranking = models.PositiveIntegerField(default = 1)
        userName = models.CharField(max_length=31, unique = True)
        picture =models.ImageField(upload_to="images")
        firstName = models.CharField(max_length=31)
        lastName = models.CharField(max_length=31)
        email = models.EmailField('email address')
        is_active = models.BooleanField(default = False)
        is_admin = models.BooleanField(default = False)
        is_online = models.BooleanField(default = False)
        login_internal = models.BooleanField(default = False)
        login_web = models.BooleanField(default = False)
        USERNAME_FIELD = 'userName'
        REQUIRED_FIELDS = []
        emailEvery= models.IntegerField(default = 0)
        has_messages = models.BooleanField(default = False)
        
        objects = CustomUserManager()

        def __unicode__(self):
            return self.userName
        
        @property
        def is_superuser(self):
            return self.is_admin

        @property
        def is_staff(self):
            return self.is_admin

        def has_perm(self, perm, obj=None):
            return self.is_admin

        def has_module_perms(self, app_label):
            return self.is_admin
        
        def get_short_name(self):
            return self.userName
            
        def get_email(self):
            return self.email
        
        def get_wins(self):
            return self.wins

        def get_losses(self):
            return self.losses

        def get_rating(self):
            return self.rating
            
        def beats(self, losingPlayer, players):
            if players == 2:
                k = 10 #The K value is an arbitrary value we choose based on how much we want
            if players > 2:
                k = 5*(players)
            #a player's score to increase/decrease after a match
            Ea = 1 / (1 + 10** ((self.rating - losingPlayer.rating) / 400))
            Eb = 1 / (1 + 10** ((losingPlayer.rating - self.rating) / 400))
            self.wins = self.wins + 1
            self.rating = math.trunc(self.rating + k * (1 - Ea))
            self.save()
            losingPlayer.losses = losingPlayer.losses + 1
            losingPlayer.rating = math.trunc(losingPlayer.rating + k * (0 - Eb))
            losingPlayer.save()

        def get_ranking(self):
            return self.ranking
            
        def get_my_friends_as_list(self):
            return ', '.join(self.friends_set.values_list('name', flat=True))

ecs 193/stebbins/forms.py
from django import forms
from stebbins.models import User

class FriendsForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput)
    class Meta:
        fields = ('name')


class RegistrationForm(forms.ModelForm):
        userName = forms.CharField(widget=forms.TextInput, label="Username")
        password1 = forms.CharField(widget=forms.PasswordInput,
                                label="Password")
        password2 = forms.CharField(widget=forms.PasswordInput,
                                label="Password (again)")

        firstName = forms.CharField(widget=forms.TextInput,label="FirstName")
        lastName = forms.CharField(widget=forms.TextInput,label="LastName")
        email = forms.EmailField(widget=forms.TextInput,label="Email")
        CHOICES=[(0,'Immediate'),
         (10,'Every 10 minutes'), (60, 'Every hour')]
        emailEvery = forms.ChoiceField(label='Notification Frequency', choices=CHOICES)
        class Meta:
                model = User
                fields = ['firstName', 'lastName', 'userName', 'email', 'password1', 'password2', 'picture', 'emailEvery'] 
        
        def clean(self):
            cleaned_data = super(RegistrationForm, self).clean()
            if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
                if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                    raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
            return self.cleaned_data

        def save(self, commit=True):
            user = super(RegistrationForm, self).save(commit=False)
            user.set_password(self.cleaned_data['password1'])
            if commit:
                user.save()
            return user
        

class AuthenticationForm(forms.Form):
    """
    Login form
    """
    userName = forms.CharField(widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ['userName', 'password']
        
class EditProfileForm(forms.ModelForm):
    email = forms.CharField(max_length=75, widget=forms.EmailInput())
    CHOICES=[(0,'Immediate'),
         (10,'Every 10 minutes'), (60, 'Every hour')]
    emailEvery = forms.ChoiceField(label='Notification Frequency', choices=CHOICES)        
    class Meta:
        model = User
        fields = ['firstName', 'lastName', 'email', 'picture', 'emailEvery'] 
        
class ChangePasswordForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput,
                                label="Password")
    password2 = forms.CharField(widget=forms.PasswordInput,
                                label="Password (again)")

    class Meta:
        model = User
        fields = ('password1', 'password2')
                
    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
        return self.cleaned_data

    def save(self, commit=True):
        user = super(ChangePasswordForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

ecs 193/stebbins/templates/stebbins/activate.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    
    <head>

        <link rel="stylesheet" type="text/css" href="{% static 'stebbins/css/change_password.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>        
        <title>ChrisCraft Account Activation</title>
    
    </head>
 
<body>

<section class="container">
    <div class="pass animate fadeIn one">

{% block content %}

    <h2>ChrisCraft Activation</h2>
    {{ message }}
    <p>Click <a href = "/accounts/login">here</a> to login again.</p>


{% endblock %}


    </div>
</section>

</body>

</html>

ecs 193/stebbins/templates/stebbins/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
</head>

<body>
	<div id="page">

    <div id="content">
    
	{% if messages %}
	<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    {% endfor %}
	</ul>
	{% endif %}
        
        {% block content %}This is the content area{% endblock %}
	
	<div class="clearfix"></div>
    </div>
	
	</div>
		
</body>
</html>

ecs 193/stebbins/templates/stebbins/change_password.html
{% load staticfiles %}
<!-- change password html -->


<!DOCTYPE html>
<html lang="en">
    
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'stebbins/css/change_password.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>        
        <title>ChrisCraft Change Password</title>
   
    </head>
 
    {% block content %}

    <body>
    
        <section class="container">
            <div class="pass animate fadeIn one">

                <h2>Change Password</h2>
                <h4>Please enter your new password:</h4>
            
                <form class="animate fadeIn one" enctype="multipart/form-data" action="/accounts/change_password/" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br>
                    <input type="SUBMIT" value="Update"/>
                </form>

            </div>
        </section>

    </body>
    </html>


    {% endblock %}

ecs 193/stebbins/templates/stebbins/change_password_success.html
{% load staticfiles %}
<!-- change password success html -->


<!DOCTYPE html>
<html lang="en">
    
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'stebbins/css/change_password.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>        
        <title>ChrisCraft Change Password</title>
   
    </head>
 
    {% block content %}

    <body>
    
        <section class="container">
            <div class="pass animate fadeIn one">

                <h2>Password successfully updated!</h2>
                <h3>Click <a href="/accounts/login/">here</a> to log in again.</h3>

            </div>
        </section>


    </body>
    
{% endblock %}

</html>

ecs 193/stebbins/templates/stebbins/compose_success.html
Your message was sent to {{recipient}}!

ecs 193/stebbins/templates/stebbins/friends.html
{% load staticfiles %}
{% block content %}

<!DOCTYPE html>
<html lang="en">


    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'stebbins/css/profile_style.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>        
        <title>ChrisCraft Add/Remove Friends</title>
    </head>


<body>

    <section class="container">
        <div class="login animate fadeIn one">
            <h2>To add or remove a friend, enter their username below:</h2>
            
            <h>{{message}}</h>
            <form action="/accounts/friends/" method='post'> 
                   {% csrf_token %}
                   {{ form.as_p }}
                    <p><input style="font-size: 1.0em;" type="submit" name="add" value="Add Friend">
                        <input style="font-size: 1.0em;" type = "submit" name = "delete" value = "Remove Friend">
                    </p>
            </form>
            <br>
            <br>
            <a href="/accounts/edit" class ="link">Edit Profile</a>
            
            </div>
    </section>
</body>
    
</html>

{% endblock %}

ecs 193/stebbins/templates/stebbins/internal_users.html
{% load staticfiles %}

<html lang = "en">
<head>
    
     <link rel="stylesheet" href="{% static 'stebbins/css/new_web_users.css' %}"/>
     <link href='http://fonts.googleapis.com/css?family=Vollkorn:400,700' rel='stylesheet' type='text/css'>
     
    <title>Game Online Users</title>
</head>

<body>

{% if request.user.is_authenticated %}
    <span><a href="/accounts/loggedin"><div class="homeButton"></div></a></span>
{% else %}
    <span><a href="/stebbins"><div class="homeButton"></div></a></span>
    <span style="float: right;"><a href= "/accounts/register" class="myButton">Register</a></span>
    <span style="float: right;"><a href= "/accounts/login" class="myButton">Login</a></span>
{% endif %}
    
<h1 class="description">
  Game Web Users.
</h1>


<div class="box-table">
<table>
  <thead>
    <tr>
    <th>Photo</th>
      <th>Name</th>
      <th>Ranking</th>
      <th>Wins</th>
      <th>losses</th>
    </tr>
  </thead>
  <tbody>
  {% for user in users%}
    <tr>
    <td class="user-photo">
      <img class="user-tumb" src="{{MEDIA_URL}}{{avatar}}{{user.user.picture}}"></td>
    <td class="styleFont">{{user.user.userName}}</td>
    <td class="styleFont">{{user.user.ranking}}</td>
    <td class="styleFont">{{user.user.wins}}</td>
    <td class="styleFont">{{user.user.losses}}</td>
    </tr>
    {% endfor %}
  </tbody>
  </table>    
</div>



</body>
</html>

ecs 193/stebbins/templates/stebbins/invalid_login.html
{%extends "stebbins/base.html" %}

{% block content %}

    <h2>{{user_name}} {{message}}</h2>
    <p>Click <a href="/accounts/login/">here</a> to login again</p>

{% endblock %}

ecs 193/stebbins/templates/stebbins/logout.html
{% extends "stebbins/base.html" %}

{% block content %}

  <h2>Logged out!</h2>
  <p>Click <a href="/accounts/login/">here</a> to login again</p>

{% endblock %}

ecs 193/stebbins/templates/stebbins/prototype_form.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'stebbins/protostyle.css' %}" />
        <title>Prototype</title>
    </head>
    <body>
        <h1>NittaCraft2</h1>    
        <form action="/stebbins/prototype/" method="get">
            <input type="text" name="q">
            <input type="submit" value="Display">
        </form>
        {% if error %}
            <p style="color: red;"> {{message}} </p>
        {%else%}
            <p style="color: white;"> {{message}} </p>
        {% endif %}
    </body>
</html>

ecs 193/stebbins/templates/stebbins/register.html
<!-- register.html -->
{% load staticfiles %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
    
        <style type="text/css">
            .signup{background-color: #222535; border-color: #DD8705;} 
            .signup .panel-body label{
                color: #FDFD2E;
                font-weight: normal;
            }
            
            .signup .panel-heading{
                background-color: #DD8705;
                color: #FDFD2E;
            }
            
            .signup .panel-footer
            {
                background-color: #DD8705;
            }
        </style>
        
        <link rel="stylesheet" type="text/css" href="{% static 'stebbins/css/register_style.css' %}"/>
        <link rel="stylesheet" href="{% static 'stebbins/css/bootstrap.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script src="{% static 'stebbins/js/jquery.js' %}"></script>
        <script src="{% static 'stebbins/js/bootstrap.min.js' %}"></script>
        <title>ChrisCraft Registration</title>
        
        <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/autopia" type="text/css"/>

    </head>

    <body>
    
    
    {% block content %}
        
    <!-- Navigation BEFORE login -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/stebbins"><img src="{% static 'stebbins/images/home/tiny_logo.png' %}"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <a href="/ranking">&nbsp;&nbsp;<i class="glyphicon glyphicon-fire"></i><span style="font-family: 'Autopiaregular', serif;">&nbsp;&nbsp;RANKING</span></a>
                    </li>
                    <li>
                <       <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Find other users now!"><i class="glyphicon glyphicon-globe"></i><span style="font-family: 'Autopiaregular', serif;">&nbsp;&nbsp;ONLINE USERS</span><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/web-players-status"><span style="font-family: 'Autopiaregular', serif;">WEB PLAYERS</span></a>
                                </li>
                                <li>
                                    <a href="/game-players-status"><span style="font-family: 'Autopiaregular', serif;">GAME PLAYERS</span></a>
                                </li>
                            </ul>
                        </li>
                    </li>
                    <li>
                        <a href="/forum"><i class="glyphicon glyphicon-comment"></i><span style="font-family: 'Autopiaregular', serif;">&nbsp;&nbsp;FORUMS</span></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">  
                    <li style= "float: right;">  
                        <a href="/accounts/login"><span style="font-family: 'Autopiaregular', serif;">LOGIN&nbsp;&nbsp;<i class="glyphicon glyphicon-queen"></i></span></a>
                    </li>
                </ul>
                
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
     
     {% csrf_token %}  
            <div class="box1">
            <div class="row">
            <!--<div class="col-md-7">-->
            <div>
             
              <div class="panel panel-default signup">
                <div class="panel-heading signup">
                <h4 class="panel-title">Sign Up</h4>
              </div>
        
        <div class="panel-body signup">
            {% if form.errors %}
<div id="form-error">
	<ul>
	{% for field in form %}
	{% if field.errors %} <label>{{ field.errors|striptags }}</label> <br>{% endif %}
	{% endfor %}
	</ul>
</div>
{% endif %}
            <form class = "form-horizontal" enctype="multipart/form-data" action="/accounts/register/" method="post">
            {% csrf_token %} 
           
           <div class="form-group">
              <label for="id_firstName" class="col-md-4 control-label">First Name:</label>
                 <div class="col-md-8">
                   <input id="id_firstName" class = "form-control" name="firstName" type="text" placeholder="Enter First Name..." required/>
                 </div>
            </div>
           
           <div class="form-group">
              <label for="id_lastName" class="col-md-4 control-label"> Last Name:</label>
              <div class="col-md-8">
               <input id="id_lastName" name="lastName" type="text" class="form-control" placeholder="Enter Last Name..."  required/>
              </div>
            </div>
            
             <div class="form-group">
              <label for="id_userName" class="col-md-4 control-label"> Username:</label>
              <div class="col-md-8">
                <input id="id_userName" name="userName" type="text" class="form-control" placeholder="Enter username..."  required/>
              </div>
            </div>

             <div class="form-group">
              <label for="id_email" class="col-md-4 control-label">Email:</label>
              <div class="col-md-8">
               <input id="id_email" name="email" class="form-control" type="text" placeholder="Enter Email..."  required/>
              </div>
            </div>

            <div class="form-group">
              <label for="id_password1" class="col-md-4 control-label">Password:</label>
              <div class="col-md-8">
               <input id="id_password1" class="form-control" name="password1" type="password" placeholder="Enter Password..."  required/>
              </div>
            </div>
        
             <div class="form-group">
              <label for="id_password2" class="col-md-4 control-label">Password (again):</label>
              <div class="col-md-8">
               <input id="id_password2" class="form-control" name="password2" type="password" placeholder="Enter Password Again..."  required/>
              </div>
            </div>

               <div class="form-group">
              <label for="id_picture" class="col-md-4 control-label">Picture:</label>
              <div class="col-md-8">
              <input id="id_picture" name="picture" type="file" class="form-control"  required/>
              </div>
            </div>
          
           <div class="form-group">
              <label for="id_emailEvery" class="col-md-4 control-label">Notification:</label>
              <div class="col-md-8">
              <select class="form-control" id="id_emailEvery" name="emailEvery">
                <option value="0">Immediate</option>
                <option value="10">Every 10 minutes</option>
               <option value="60">Every hour</option>
             </select>
              </div>
           </div>
           
          
            
           
          <!-- <p><label for="id_firstName">First Name:</label> <input id="id_firstName" name="firstName" type="text" placeholder="Enter First Name..."/></p>
            
            <p><label for="id_lastName">Last Name:</label> <input id="id_lastName" name="lastName" type="text" placeholder="Enter Last Name..."/></p>
            <p><label for="id_userName">Username:</label> <input id="id_userName" name="userName" type="text" placeholder="Enter username..."/></p>
            <p><label for="id_email">Email:</label> <input id="id_email" name="email" class="form-control" type="text" placeholder="Enter Email..."/></p>
            <p><label for="id_password1">Password:</label> <input id="id_password1" class="form-control" name="password1" type="password" placeholder="Enter Password..."/></p>
            <p><label for="id_password2">Password (again):</label> <input id="id_password2" class="form-control" name="password2" type="password"placeholder="Enter Password again..." /></p>
            <p><label for="id_picture">Picture:</label> <input id="id_picture" name="picture" type="file" /></p>
            <p><label for="id_emailEvery">Notification Frequency:</label> 
            <select class="form-control" id="id_emailEvery" name="emailEvery">
            <option value="0">Immediate</option>
            <option value="10">Every 10 minutes</option>
            <option value="60">Every hour</option>
            </select></p>-->
     
         <input type = "submit" class="register-button" value="Register" />
        </form>
         </div> <!--for the body control-->
        
       
         
          
       
   </div>
   </div>
   </div>
   </div>
           
        
    
    {% endblock %}

        </body>
</html>