ecs 193/django-messages/django_messages/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView

from django_messages.views import *

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(permanent=True, url='inbox/'), name='messages_redirect'),
    url(r'^inbox/$', inbox, name='messages_inbox'),
    url(r'^outbox/$', outbox, name='messages_outbox'),
    url(r'^compose/$', compose, name='messages_compose'),
    url(r'^compose/(?P<recipient>[\w.@+-]+)/$', compose, name='messages_compose_to'),
    url(r'^reply/(?P<message_id>[\d]+)/$', reply, name='messages_reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', view, name='messages_detail'),
    url(r'^delete/(?P<message_id>[\d]+)/$', delete, name='messages_delete'),
    url(r'^undelete/(?P<message_id>[\d]+)/$', undelete, name='messages_undelete'),
    url(r'^trash/$', trash, name='messages_trash'),
)

ecs 193/ecs193/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^stebbins/', 'stebbins.views.oldindex'),
    url(r'^/$', include('stebbins.urls', namespace="stebbins")),
    url(r'', include('stebbins.urls', namespace="stebbins")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^messages/', include('django_messages.urls')),
    url(r'^accounts/login/$', 'stebbins.views.login'),
    url(r'^accounts/logout/$', 'stebbins.views.logout'),
    url(r'^accounts/loggedin/$', 'stebbins.views.loggedin'),
    url(r'^accounts/profile/$', 'stebbins.views.profile'),
    url(r'^accounts/invalid/$', 'stebbins.views.invalid_login'),
    url(r'^accounts/register/$', 'stebbins.views.register_user'),
    url(r'^accounts/register_success/$', 'stebbins.views.register_success'),
    url(r'^accounts/internalLogin/$', 'stebbins.views.internalLogin'),
     url(r'^accounts/password_reset/$', 'django.contrib.auth.views.password_reset', kwargs={'template_name' : 'password_reset.html'}),
    url(r'^accounts/password_reset_done/$', 'django.contrib.auth.views.password_reset_done', kwargs={'template_name' : 'password_reset_done.html'}, name='password_reset_done'),
    url(r'^accounts/password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', kwargs={'template_name' : 'password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^accounts/activate/(?P<userName>\w{1,50})/(?P<activation_key>\w{1,50})/$', 'stebbins.views.activate'),
	url(r'^web-players-status/$', 'stebbins.views.webLoggedIn'),
    url(r'^game-players-status/$', 'stebbins.views.internalLoggedIn'),
    url(r'^accounts/password_reset/$', 'django.contrib.auth.views.password_reset'),
    url(r'^accounts/password_reset_done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^accounts/password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^accounts/password_reset_complete/$', 'django.contrib.auth.views.password_reset_complete',  name='password_reset_complete'),
    url(r'^downloads/$', 'stebbins.views.downloads'),
    url(r'^accounts/edit/$', 'stebbins.views.edit_profile'),
    url(r'^accounts/edit_profile_success/$', 'stebbins.views.edit_profile_success'),
    url(r'^accounts/change_password/$', 'stebbins.views.change_password'),
    url(r'^accounts/change_password_success/$', 'stebbins.views.change_password_success'),
    url(r'^compose_success/$', 'stebbins.views.compose_success'),    
    url(r'^send_something/$', 'stebbins.views.send_something'),
    url(r'^forum/forum/(\d+)/$', 'forum.views.forum'),
    url(r'^forum/thread/(\d+)/$', 'forum.views.thread'), 
    url(r'^forum/post/(new_thread|reply)/(\d+)/$', 'forum.views.post'),
    url(r'^forum/reply/(\d+)/$', 'forum.views.reply'),
    url(r'^forum/profile/(\d+)/$', 'forum.views.profile'),
    url(r'^forum/new_thread/(\d+)/$', 'forum.views.new_thread'),
    url(r'^forum/$', 'forum.views.main'),
    url(r'^accounts/internalLogin/$', 'stebbins.views.internalLogin'),
    url(r'^accounts/internalLogout/$', 'stebbins.views.internalLogout'),
    url(r'^accounts/internalUpdate/$', 'stebbins.views.internalUpdate'),
     url(r'^accounts/friends/$', 'stebbins.views.friends'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecs 193/forum/urls.py
from django.conf.urls import include, url, patterns
from forum.models import *

urlpatterns = patterns('forum.views',
    (r"^forum/(\d+)/$", "forum"),
    (r"^thread/(\d+)/$", "thread"),
    (r"^post/(new_thread|reply)/(\d+)/$", "post"),
    (r"^reply/(\d+)/$", "reply"),
    (r"^profile/(\d+)/$", "profile"),
    (r"^new_thread/(\d+)/$", "new_thread"),
    (r"", "main"),
)

ecs 193/django-messages/django_messages/models.py
from django.conf import settings
from django.db import models
from django.db.models import signals
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class MessageManager(models.Manager):

    def inbox_for(self, user):
        """
        Returns all messages that were received by the given user and are not
        marked as deleted.
        """
        return self.filter(
            recipient=user,
            recipient_deleted_at__isnull=True,
        )

    def outbox_for(self, user):
        """
        Returns all messages that were sent by the given user and are not
        marked as deleted.
        """
        return self.filter(
            sender=user,
            sender_deleted_at__isnull=True,
        )

    def trash_for(self, user):
        """
        Returns all messages that were either received or sent by the given
        user and are marked as deleted.
        """
        return self.filter(
            recipient=user,
            recipient_deleted_at__isnull=False,
        ) | self.filter(
            sender=user,
            sender_deleted_at__isnull=False,
        )


@python_2_unicode_compatible
class Message(models.Model):
    """
    A private message from user to user
    """
    subject = models.CharField(_("Subject"), max_length=120)
    body = models.TextField(_("Body"))
    sender = models.ForeignKey(AUTH_USER_MODEL, related_name='sent_messages', verbose_name=_("Sender"))
    recipient = models.ForeignKey(AUTH_USER_MODEL, related_name='received_messages', null=True, blank=True, verbose_name=_("Recipient"))
    parent_msg = models.ForeignKey('self', related_name='next_messages', null=True, blank=True, verbose_name=_("Parent message"))
    sent_at = models.DateTimeField(_("sent at"), null=True, blank=True)
    read_at = models.DateTimeField(_("read at"), null=True, blank=True)
    replied_at = models.DateTimeField(_("replied at"), null=True, blank=True)
    sender_deleted_at = models.DateTimeField(_("Sender deleted at"), null=True, blank=True)
    recipient_deleted_at = models.DateTimeField(_("Recipient deleted at"), null=True, blank=True)

    objects = MessageManager()

    def new(self):
        """returns whether the recipient has read the message or not"""
        if self.read_at is not None:
            return False
        return True

    def replied(self):
        """returns whether the recipient has written a reply to this message"""
        if self.replied_at is not None:
            return True
        return False

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return ('messages_detail', [self.id])
    get_absolute_url = models.permalink(get_absolute_url)

    def save(self, **kwargs):
        if not self.id:
            self.sent_at = timezone.now()
        super(Message, self).save(**kwargs)

    class Meta:
        ordering = ['-sent_at']
        verbose_name = _("Message")
        verbose_name_plural = _("Messages")


def inbox_count_for(user):
    """
    returns the number of unread messages for the given user but does not
    mark them seen
    """
    return Message.objects.filter(recipient=user, read_at__isnull=True, recipient_deleted_at__isnull=True).count()

# fallback for email notification if django-notification could not be found
if "notification" not in settings.INSTALLED_APPS and getattr(settings, 'DJANGO_MESSAGES_NOTIFY', True):
    from django_messages.utils import new_message_email
    signals.post_save.connect(new_message_email, sender=Message)

ecs 193/django-messages/django_messages/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

if "notification" in settings.INSTALLED_APPS and getattr(settings, 'DJANGO_MESSAGES_NOTIFY', True):
    from notification import models as notification
else:
    notification = None

from django_messages.models import Message
from django_messages.fields import CommaSeparatedUserField

class ComposeForm(forms.Form):
    """
    A simple default form for private messages.
    """
    recipient = CommaSeparatedUserField(label=_(u"Recipient"))
    subject = forms.CharField(label=_(u"Subject"), max_length=120)
    body = forms.CharField(label=_(u"Body"),
        widget=forms.Textarea(attrs={'rows': '12', 'cols':'55'}))
    
        
    def __init__(self, *args, **kwargs):
        recipient_filter = kwargs.pop('recipient_filter', None)
        super(ComposeForm, self).__init__(*args, **kwargs)
        if recipient_filter is not None:
            self.fields['recipient']._recipient_filter = recipient_filter
    
                
    def save(self, sender, parent_msg=None):
        recipients = self.cleaned_data['recipient']
        subject = self.cleaned_data['subject']
        body = self.cleaned_data['body']
        message_list = []
        for r in recipients:
            msg = Message(
                sender = sender,
                recipient = r,
                subject = subject,
                body = body,
            )
            if parent_msg is not None:
                msg.parent_msg = parent_msg
                parent_msg.replied_at = timezone.now()
                parent_msg.save()
            msg.save()
            message_list.append(msg)
            if notification:
                if parent_msg is not None:
                    notification.send([sender], "messages_replied", {'message': msg,})
                    notification.send([r], "messages_reply_received", {'message': msg,})
                else:
                    notification.send([sender], "messages_sent", {'message': msg,})
                    notification.send([r], "messages_received", {'message': msg,})
        return message_list

ecs 193/django-messages/django_messages/templates/django_messages/base.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}
{% block content %}  
{% endblock %}
{% block sidebar %}
<ul class="subnavilist">
    <li><a href="{% url 'messages_inbox' %} ">&raquo;&nbsp;{% trans "Inbox" %}</a></li>
    <li><a href="{% url 'messages_outbox' %} ">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
    <li><a href="{% url 'messages_compose' %} ">&raquo;&nbsp;{% trans "New Message" %}</a></li>
    <li><a href="{% url 'messages_trash' %} ">&raquo;&nbsp;{% trans "Trash" %}</a></li>
</ul>
{% endblock %}

ecs 193/django-messages/django_messages/templates/django_messages/compose.html
{% load i18n %} 
 {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'stebbins/css/inbox_style.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>        
        <script type="text/javascript" src="{% static 'stebbins/js/jscript-inbox.js' %}"></script>
        <link rel="stylesheet" href="{% static 'stebbins/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'stebbins/css/bootstrap.css' %}">
        <title>ChrisCraft: New Message</title>
        <!--<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content=""> -->

    </head>

<body>
<div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li style="color: #ffffff;" class="sidebar-brand">
                    
                        Friends List 
                 
                </li>
                <table style="width:85%; font-size: 1.2em; color: #ffffff;">
                {% for name in friendsname %}
            <tr>
            	<td><img src="{{ MEDIA_URL }}{{ name.2 }}" alt="Avatar" width="50" height="50"></img></td>
            	<td>{{name.0}}</td>
            	<td>{{name.1}}</td>
            
            </tr>
                {%endfor%}
                </table>
                <!--
                <li>
                    <a href="#">Shortcuts</a>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li> -->
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">

 <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Friends List</a>


<!--<h1>{% trans "Compose Message"%}</h1>-->

<!--{{ request.user.firstName }} -->

{% block content %}
<!--
<form action="" method="post">
{% csrf_token %} 
<table>
<tr><th><label for="id_recipient">Recipient:</label></th><td><input id="id_recipient" name="recipient" type="text" /></td></tr>
<tr><th><label for="id_subject">Subject:</label></th><td><input id="id_subject" maxlength="120" name="subject" type="text" /></td></tr>
<tr><th><label for="id_body">Body:</label></th><td><textarea cols="55" id="id_body" name="body" rows="12">
</textarea></td></tr>
</table>
<input type="submit" value="{% trans "Send" %} &raquo;"/>
</form>

-->

<form action="" method="post">
{% csrf_token %} 
<div id="form-error">
	<ul>
	
	
	
	</ul>
</div>

<div class="tab-pane" id="compose">
      
     
      <div class="back-box">
    <div class="content-container clearfix">
    
     
            <a href="/messages/inbox" style="display:right;" class ="btn">Inbox  <span class="glyphicon glyphicon-inbox"></span></a>
            <a href="/messages/outbox" style="display:right;" class ="btn">Sent Mail  <span class="glyphicon glyphicon-send"></span></a>
            <a href="/messages/trash" style="display:right;" class ="btn">Trash  <span class="glyphicon glyphicon-trash"></span></a>
           <a style="float: right; margin: 5px; font-size: 1.4em;" href="/accounts/edit">Profile</a>
            <a style="float: right; margin: 5px; font-size: 1.4em;" href="/accounts/loggedin">Home</a>
           
           <br>
           <br>
    
        <h1 class="content-title">Compose</h1>
        <div class="col-md-12">
                
            
            <div class="form-group">
                {% if form.recipient.errors %} <label>{{ form.recipient.errors|striptags }}</label> <br>{% endif %}
                <input id="id_recipient" rows="2" name="recipient" type="text" class="form-control" placeholder="To" />
            </div>
            
            <!--
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Cc" />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Bcc" />
            </div>
            -->
            
            <div class="form-group">
                {% if form.subject.errors %} <label>{{ form.subject.errors|striptags }}</label> <br>{% endif %}
                <input id="id_subject" name="subject" type="text" class="form-control" placeholder="Subject" />
            </div>
            {% if form.body.errors %} <label>{{ form.body.errors|striptags }}</label> <br>{% endif %}
            <textarea id="id_body" class="form-control" name="body" rows="12" placeholder="message"></textarea>
            
            <div class="btn-send">
            
                <input class="btn-success btn-lg" type="submit" value="Send"/>
            <!--<button class="btn btn-success btn-lg"><input type="submit"><span class="glyphicon glyphicon-send"></span> Send</input></button>-->
            
            </div>
        </div>
    </div>
    </div>
</div>

    
</form>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->



    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

<!--
<form action="" method="post">
{% csrf_token %} 
<table>
{{ form.as_table }}
</table>
<input type="submit" value="{% trans "Send" %} &raquo;"/>
</form>
-->
{% endblock %}

</body>
</html>

ecs 193/django-messages/django_messages/templates/django_messages/compose_success.html
Your message was sent successfully.

ecs 193/django-messages/django_messages/templates/django_messages/inbox.html
{% load i18n %} 
{% load url from future %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'stebbins/css/inbox_style.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>        
        <script type="text/javascript" src="{% static 'stebbins/js/jscript-inbox.js' %}"></script>
        <link rel="stylesheet" href="{% static 'stebbins/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'stebbins/css/bootstrap.css' %}">
        <title>ChrisCraft: {{ request.user.firstName }}'s Inbox</title>
    </head>


<body>

<div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li style="color: #ffffff;" class="sidebar-brand">
                    
                        Friends List 
                 
                </li>
                <table style="width:85%; font-size: 1.2em; color: #ffffff;">
                {% for name in friendsname %}
            <tr>
            	<td><img src="{{ MEDIA_URL }}{{ avatar }}{{ name.2 }}" alt="Avatar" width="50" height="50"></img></td>
            	<td>{{name.0}}</td>
            	<td>{{name.1}}</td>
            
            </tr>
                {%endfor%}
                </table>
                <!--
                <li>
                    <a href="#">Shortcuts</a>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li> -->
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">

 <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Friends List</a>


  <div class="tab-pane active" id="inbox">
      
      <div class="back-box box" style="display: block;">
           <div class="content-container clearfix">
               <div class="col-md-12">
                                   {% for message in messages %}
                        <li class="{{ message.tags }}">
                            {{ message }}
                        </li>
                    {% endfor %}
               <a href="/messages/compose" style="display:right;" class ="btn">Compose  <span class="glyphicon glyphicon-pencil"></span></a>
                   <a href="/messages/outbox" style="display:right;" class ="btn">Sent Mail  <span class="glyphicon glyphicon-send"></span></a>
                   <a href="/messages/trash" style="display:right;" class ="btn">Trash  <span class="glyphicon glyphicon-trash"></span></a>
                   <a style="float: right; margin: 5px; font-size: 1.4em;" href="/accounts/edit">Profile</a>
                   <a style="float: right; margin: 5px; font-size: 1.4em;" href="/accounts/loggedin">Home</a>
                   <br />
                   <br />

                   <h1 class="content-title">{{ request.user.firstName }}'s Inbox</h1> 
                   
                   
                   <!--<input type="search" placeholder="Search Mail" class="form-control mail-search" /> -->
                  
                     
                     {% block content %}
                   <ul class="mail-list">
                     
    
                            
                            {% if message_list %} 
                            
                            {% for message in message_list %} 
                                <span style="float:right;"><a href="{% url 'messages_delete' message.id %}">{% trans "delete" %}</a></span>
                            
                                 <li>
                                    <a href="{{message.get_absolute_url }}">
                                        <span class="mail-sender">{{ message.sender }}</span>
                                        <p style="text-align:left;">
                                        {{ message.subject }}
                                        <span style="float:right;">{{ message.sent_at|date:_("DATETIME_FORMAT") }}</span>
                                        </p>
                                        <!--<span class="mail-message-preview">You have ten more subscriptions click her...</span>-->
                                    </a>
                                 </li>
                                        {% if message.new %}<strong>{% endif %}
                                        {% if message.replied %}<em>{% endif %}
                                        {% if message.replied %}</em>{% endif %}
                                        {% if message.new %}</strong>{% endif %}</td>
                                    <!--<td><a href="{% url 'messages_delete' message.id %}">{% trans "delete" %}</a></td>-->
                                </tr>
                            {% endfor %}
                                <!--</tbody> -->
                            </table>
                            {% else %}
                            <p>{% trans "No messages." %}</p>
                            {% endif %}  
                        
                      
                   </ul>
                   {% endblock %}
               </div>
           </div>
       </div>
      </div>
  <!--</div>-->
</div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->



    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>



</body>

    
</html>

ecs 193/django-messages/django_messages/templates/django_messages/nameright.html
{{name}}
whoa!

ecs 193/django-messages/django_messages/templates/django_messages/new_message.html
{% load i18n %}
{% load url from future %}

{% blocktrans with recipient=message.recipient sender=message.sender %}Hello {{ recipient }},

you received a private message from {{ sender }} with
the following contents:{% endblocktrans %}

{{ message.body|safe }}

--
{% blocktrans %}Sent from {{ site_url }}{% endblocktrans %}
{% trans "Inbox" %}: {{ site_url }}{% url 'messages_inbox' %}
{% trans "Reply" %}: {{ site_url }}{% url 'messages_reply' message.pk %}     

ecs 193/django-messages/django_messages/templates/django_messages/new_message_email.html
Hello {{recipient}},
<br><br>
You have a new message from {{sender}}:
<br><br>
{{message}}

ecs 193/django-messages/django_messages/templates/django_messages/outbox.html
{% load i18n %} 
{% load url from future %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'stebbins/css/inbox_style.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>        
        <script type="text/javascript" src="{% static 'stebbins/js/jscript-inbox.js' %}"></script>
        <link rel="stylesheet" href="{% static 'stebbins/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'stebbins/css/bootstrap.css' %}">
        <title>ChrisCraft: Sent Mail</title>
    </head>

<body>
<div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li style="color: #ffffff;" class="sidebar-brand">
                    
                        Friends List 
                 
                </li>
                <table style="width:85%; font-size: 1.2em; color: #ffffff;">
                {% for name in friendsname %}
            <tr>
            	<td><img src="{{ MEDIA_URL }}{{ name.2 }}" alt="Avatar" width="50" height="50"></img></td>
            	<td>{{name.0}}</td>
            	<td>{{name.1}}</td>
            
            </tr>
                {%endfor%}
                </table>
                <!--
                <li>
                    <a href="#">Shortcuts</a>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li> -->
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">

 <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Friends List</a>

 
 <div class="tab-pane active" id="inbox">
      
      <div class="back-box" style="display: block;">
           <div class="content-container clearfix">
               <div class="col-md-12">
                   
                    <a href="/messages/inbox" style="display:right;" class ="btn">Inbox  <span class="glyphicon glyphicon-inbox"></span></a>
                       <a href="/messages/compose" style="display:right;" class ="btn">Compose  <span class="glyphicon glyphicon-pencil"></span></a>
                       <a href="/messages/trash" style="display:right;" class ="btn">Trash  <span class="glyphicon glyphicon-trash"></span></a>
                        <a style="float: right; margin: 5px; font-size: 1.4em;" href="/accounts/edit">Profile</a>
                        <a style="float: right; margin: 5px; font-size: 1.4em;" href="/accounts/loggedin">Home</a>
                       <br />
                       <br />

                   
                   <h1 class="content-title">Sent Mail</h1> 
                       
                      
    
                        {% block content %} 
                        
                        <ul class="mail-list">
                        <!--<h1>{% trans "Sent Messages" %}</h1>-->
                       
                        {% if message_list %}
                        <!--
                        <table class="messages"> 
                            <thead>
                                <tr><th>{% trans "Recipient" %}</th><th>{% trans "Subject" %}</th><th>{% trans "Sent" %}</th><th>{% trans "Action" %}</th></tr>
                            </thead>
                            <tbody> -->
                        {% for message in message_list %} 
                            <li>
                                <a href="{{message.get_absolute_url }}">
                                    <span class="mail-sender">{{ message.recipient }}</span>
                                    <p style="text-align:left;">
                                        {{ message.subject }}
                                        <span style="float:right;">{{ message.sent_at|date:_("DATETIME_FORMAT") }}</span>
                                        </p>
                                    <!--<span class="mail-message-preview">You have ten more subscriptions click her...</span>-->
                                </a>
                            </li>
                            <!--<tr>
                                <td></td>
                                <td>
                                <a href="{{ message.get_absolute_url }}">{{ message.subject }}</a>
                                </td>
                                <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
                                <td><a href="{% url 'messages_delete' message.id %}?next={% url 'messages_outbox' %}">{% trans "delete" %}</a></td>
                            </tr>-->
                        {% endfor %}
                           
                        {% else %}
                        <p>{% trans "No messages." %}</p>
                        {% endif %}
                        </ul>
                        {% endblock %}
                         </div>
           </div>
       </div>
      </div>
</div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->



    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>
</html>